### ISSUE TITLE
Subclass from SimpleFormObject::Base rather than include SimpleFormObject

### ISSUE THREAD

**Issue by jfeaver** [reinteractive-open/simple_form_object#3]
This is just a suggestion but it makes more sense in my mind to inherit from a base object since the form objects I am building _is a_ `SimpleFormObject::Base`.  Including a module gives the impression that my object plays the role of a `SimpleFormObject` in addition to its primary purpose.

**Comment by mikel** [comment]
Hey there, good idea, but yeah, this is just a preference. The current system works and I like preferring inclusion over inheritance :)
